services:
  - type: web
    name: schoolwaze-demo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: NODE_ENV
        value: production
